---
title: "COVID-19 Graphs"
author: "Emma Spors"
date: "9/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, include=TRUE}
library(tidyverse)
library(lubridate)
library(imputeTS)
library(car)
source("covid_functions.r")
```

```{r, echo=FALSE,include=TRUE, results='hide'}
covid_counties <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")
covid_states <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")

county_population <- read_csv("county_population.csv")
state_population <- read_csv("state_population.csv")
united_states_pop <- read_csv("united_states_pop.csv")

```

```{r}
covidCounties <- covid_rates(covid_counties, county_population)
covidStates <- covid_rates(covid_states, state_population)
covidUs <- us_rates(covid_states, united_states_pop)
```


```{r}
covidCountiesR <- covidCounties %>%
  filter(fips >= 46000 & fips < 47000)
ts_counties <- ggplot(data = covidCountiesR, aes(x = date)) + 
  geom_line(aes(y = cases, color = fips), size = 0.75) + 
  theme_minimal() 
ts_counties
```

```{r}
ts_states <- ggplot(data = covidStates, aes(x = date)) + 
  geom_line(aes(y = cases, color = state.x), size = 0.75) + 
  theme_minimal() 
ts_states
```

```{r}
cumulativeCounties <- cumulative_county(covid_counties, county_population)
cumulativeStates <- cumulative_state(covid_states, state_population)
cumulativeUS <- cumulative_us(covid_states, united_states_pop)
```

```{r}
mapData <- cumulativeCounties
county <- map_data("county")
county$subregion <- replace(county$subregion, county$subregion == 'shannon', 'oglala lakota')
mapData$county.x <- tolower(mapData$county.x)
colnames(mapData)[colnames(mapData) == "county.x"] <- "subregion"
counties <- inner_join(county, mapData, by = "subregion")
```

```{r}
map_base <- ggplot(data = county, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "gray")  + 
  ylab('') + 
  xlab('') + 
  theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank())
map_base 
```

```{r}
map <- map_base + 
  geom_polygon(data = counties, aes(fill = cases), color = "white") + 
  scale_fill_gradient(low = 'white', high = 'darkolivegreen4') 

map
```

```{r}
mapData <- cumulativeStates
state <- map_data("state")

mapData$state.x <- tolower(mapData$state.x)
colnames(mapData)[colnames(mapData) == "state.x"] <- "region"
states <- inner_join(state, mapData, by = "region")
```

```{r}
map_base <- ggplot(data = state, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "gray")  + 
  ylab('') + 
  xlab('') + 
  theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank())
map_base 
```
```{r}
map <- map_base + 
  geom_polygon(data = states, aes(fill = cases), color = "white") + 
  scale_fill_gradient(low = "white", high = "darkolivegreen4")

map
```
```{r}
covidC_mn <- cumulativeCounties %>%
  filter(state.x == 'Minnesota')
covidS_mn <- cumulativeStates %>%
  filter(state.x == 'Minnesota')

sir_df <- sir_counties(covidC_mn, covidS_mn)

sir <- sir_df %>%
  filter(significantC == 1)
```

```{r}
dodge <- position_dodge(width = 0.9)
custom <- c("#335C67", "#E09F3E")
sir_bar <- ggplot(sir, aes(y = (sir-1), x = reorder(county.x, sir), fill = typeC)) + 
  geom_bar(stat = "identity", position = dodge) + 
  geom_errorbar(aes(ymax = (usir - 1), ymin = (lsir - 1)), position = dodge, width = 0.25) + 
  xlab("County") + 
  ylab("SIR for cases") + 
  labs(fill = "Type") + 
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_fill_manual(values = custom) + 
  theme(legend.position = "none")
sir_bar
```

```{r}
sir_df <- sir_states(cumulativeStates, cumulativeUS)

sir <- sir_df %>%
  filter(significantC == 1)
```

```{r}
dodge <- position_dodge(width = 0.9)
custom <- c("#335C67", "#E09F3E")
sir_bar <- ggplot(sir, aes(y = (sir-1), x = reorder(state.x, sir), fill = typeC)) + 
  geom_bar(stat = "identity", position = dodge) + 
  geom_errorbar(aes(ymax = (usir - 1), ymin = (lsir - 1)), position = dodge, width = 0.25) + 
  xlab("County") + 
  ylab("SIR for cases") + 
  labs(fill = "Type") + 
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_fill_manual(values = custom) + 
  theme(legend.position = "none")
sir_bar
```

